### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RSoulatIOHK** [RSoulatIOHK/MarloweCBMC#23]
- [ ] Move to UTXO model
- [ ] Have Party tokens, and add addresses to the internal
- [ ] Add a datum type
- [ ] Move to the types from the spec 😅 
- [ ] Add more properties
- [ ] Add the other Marlowe contracts
- [ ] Generate the tree from Json

Better trace viewer
- [ ] Reparse the XML to only display meaningful stuff (MVP on swap example)
- [ ] Display the succesful properties
- [ ] Remove some "Technical" properties and only display if failed
